// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace online_voting_system0910.Models;

public partial class voting0910Context : DbContext
{
    public voting0910Context(DbContextOptions<voting0910Context> options)
        : base(options)
    {
    }

    public virtual DbSet<VotingItem> VotingItem { get; set; }

    public virtual DbSet<VotingRecord> VotingRecord { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VotingItem>(entity =>
        {
            entity.Property(e => e.VotingItemName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<VotingRecord>(entity =>
        {
            entity.Property(e => e.Voter)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.VotingItem).WithMany(p => p.VotingRecord)
                .HasForeignKey(d => d.VotingItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VotingRecord_VotingItem");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}