// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace online_voting_system0910.Models;

public partial class VotingRecord
{
    public int VotingRecordId { get; set; }

    public string Voter { get; set; }

    public int VotingItemId { get; set; }

    public virtual VotingItem VotingItem { get; set; }
}