// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace online_voting_system0910.Models;

public partial class VotingItem
{
    public int VotingItemId { get; set; }

    public string VotingItemName { get; set; }

    public virtual ICollection<VotingRecord> VotingRecord { get; set; } = new List<VotingRecord>();
}